logging:
  version: 1
  formatters:
    formatter:
      format: '%(asctime)s - %(levelname)s [%(name)s:%(module)s]: %(message)s'
      datefmt: '%Y/%m/%d %H:%M:%S'
  handlers:
    #these handlers say: for ERROR an higher, log on console. for DEBUG log on file
    console:
      class: 'logging.StreamHandler'
      formatter: 'formatter'
      level: 'DEBUG'
      stream: 'ext://sys.stdout'
    file:
      class : 'logging.FileHandler'
      formatter: 'formatter'
      level: 'DEBUG'
      filename: 'D:\Zipline\20100101_20150101_500S\crocoubot_runs\logs\quant_workflow-debug.log'
  root:
    level: 'DEBUG'
    handlers: ['file', 'console']
quant_workflow:
  run_mode: 'backtest'
  results_path: 'D:\Zipline\20100101_20150101_500S\crocoubot_runs\results'
  fill_limit: 5
  trade_resample_rule: '15T'
  trade_history_ndays: 20
  trade_frequency: 'weekly'
  trade_days_offset: 1
  trade_minutes_offset: 60
  trade_horizon_ncycles: 1
  train_resample_rule: '15T'
  train_history_ndays: 250
  train_frequency: 'weekly'
  train_days_offset: 0
  train_minutes_offset: 60
  alert_level: 'NONE'
  execution_timeout: 180.
  open_order_timeout: 3600.
  oracle:
    method: library
    module_path: alphai_crocubot_oracle.oracle
    oracle_class_name: CrocubotOracle
    oracle_arguments:
      data_transformation:
        feature_config_list:
          -
            name: close
            transformation:
              name: 'log-return'
            normalization: standard
            nbins: 6
            is_target: True
        exchange_name: 'NYSE'
        features_ndays: 10
        features_resample_minutes: 15
        features_start_market_minute: 60
        prediction_frequency_ndays: 1
        prediction_market_minute: 60
        target_delta_ndays: 1
        target_market_minute: 60
      n_training_samples_benchmark: 1000
      train_path: 'D:\Zipline\20100101_20150101_500S\crocoubot_runs\train'
      tensorboard_log_path: 'D:\Zipline\20100101_20150101_500S\crocoubot_runs\temp'
      covariance_method: 'Ledoit'
      covariance_ndays: 9
      model_save_path: 'D:\Zipline\20100101_20150101_500S\crocoubot_runs\model'
      d_type: float32
      tf_type: 32
      random_seed: 0
      predict_single_shares: True
      n_epochs: 200
      n_retrain_epochs: 5
      n_training_samples: 15800
      learning_rate: 0.0001
      batch_size: 100
      cost_type: 'bayes'
      n_train_passes: 16
      n_eval_passes: 16
      resume_training: True
      n_series: 1
      n_features_per_series: 271
      n_forecasts: 1
      n_classification_bins: 6
      classify_per_series: False
      normalise_per_series: False
      layer_heights:
      - 100
      - 100
      - 100
      - 100
      - 100
      - 100
      - 100
      - 100
      - 100
      - 100
      layer_widths:
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      activation_functions:
      - relu
      - relu
      - relu
      - relu
      - relu
      - relu
      - relu
      - relu
      - relu
      - relu
      INITIAL_ALPHA: 0.2
      INITIAL_WEIGHT_UNCERTAINTY: 0.01
      INITIAL_BIAS_UNCERTAINTY: 0.01
      INITIAL_WEIGHT_DISPLACEMENT: 0.2
      INITIAL_BIAS_DISPLACEMENT: 0.01
      USE_PERFECT_NOISE: False
      double_gaussian_weights_prior: True
      wide_prior_std: 0.8
      narrow_prior_std: 0.0001
      spike_slab_weighting: 0.5
  portfolio:
    max_abs_individual_weight: 0.2
    max_abs_pos_gross_exposure: 0.75
    max_abs_neg_gross_exposure: 0.75
    margin_ratio: 1.0
    max_annualised_std: 0.3
  universe:
    method: 'liquidity'
    nassets: 400
    ndays_window: 60
    update_frequency: 'monthly'
    avg_function: 'median'
    fill_limit: 5
    dropna: False
zipline:
  zipline_root: 'D:\Zipline\20100101_20150101_500S\zipline_root'
  start_date: '20110401'
  end_date: '20110415'
  capital_base: 1000000.
  data_frequency: 'minute'
  data_bundle: 'test_bundle'
  slippage_type: 'TradeAtTheOpenSlippageModel'
  spread: 0.
  open_close_fraction: 0.
  volume_limit: 0.
  price_impact: 0.
  commission_type: 'PerShare'
  cost: 0.0005
  min_trade_cost: 1.
live_clock_configuration:
  host: 'localhost'
  port: 45672
  queue_name: 'clock-pulse'